### ISSUE TITLE
Running without indicating an app doesn't run any tests

### ISSUE THREAD

**Issue by Moini** [doctormo/django-autotest#2]
If I just run the test suite without adding which app I want to test, it doesn't seem to find the tests (at least it's running 0 tests after building the test db).
If I add the app's name to the command, it runs the corresponding tests.

Just in case the working directory matters: 
I was running it from the root directory of our inkscape-web branch.

(using 1.3 from pypi)

**Comment by Moini** [comment]
I just checked if your renaming of the tests files could have solved the issue, but it didn't, unfortunately.

**Comment by doctormo** [comment]
This is very much unable to reproduce. Running here without app does this:

(doctormo@delen[PY])-(~/Projects/inkscape/web)
$ dj autotest
Creating test database for alias 'default'...
 -= Testing Service Running; use [CTRL]+[C] to exit =-

 * Running tests!

........................F.....................................F..F..............F................F................

...

----------------------------------------------------------------------
Ran 114 tests in 75.106s

**Comment by Moini** [comment]
This is what it looks like for me... :/ :
(doesn't matter if pythonenv is activated or not)

(pythonenv)maren@tommy ..../inkscape-web $ ./utils/manage autotest
Err in alert: cmstabs.page_published_alert
Page already has 'alerts' reverse lookup
Creating test database for alias 'default'...
Destroying old test database 'default'...
Err in alert: cmsdiff.page_published_alert
Page already has 'alerts' reverse lookup
Err in alert: cmstabs.page_published_alert
Page already has 'alerts' reverse lookup
Err in alert: resource.resource_alert
Resource already has 'alerts' reverse lookup
Err in alert: alerts.message_alert
Message already has 'alerts' reverse lookup
Err in alert: alerts.test_message_alert
Message already has 'test_alerts' reverse lookup

 -= Testing Service Running; use [CTRL]+[C] to exit =-

Err in alert: cmstabs.page_published_alert
Page already has 'alerts' reverse lookup

 * Running tests!


----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Still working!

Select failures to target or press enter to re-run all:

**Comment by Moini** [comment]
Thanks :)
